apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
spec:
  type: NodePort
  selector:
    app: devops-task-manager
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30007
